sudo: required
language: minimal
dist: xenial

before_script:
  - ./kind/k8s-create.sh

script:
  - ./kind/launch.sh

after_success:
  - echo "Push image to Docker Hub"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./build-image.sh
